swagger: "2.0"
info:
    title: Todo Service
    description: Service for managing todos
    version: ""
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /login:
        post:
            tags:
                - auth
            summary: login auth
            description: Login to the system
            operationId: auth#login
            parameters:
                - name: LoginRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/AuthLoginRequestBody'
                    required:
                        - username
                        - password
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/AuthLoginResponseBody'
            schemes:
                - http
    /logout:
        post:
            tags:
                - auth
            summary: logout auth
            description: Logout of the system
            operationId: auth#logout
            parameters:
                - name: LogoutRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/AuthLogoutRequestBody'
                    required:
                        - token
            responses:
                "200":
                    description: OK response.
            schemes:
                - http
    /register:
        post:
            tags:
                - auth
            summary: register auth
            description: Register a new user
            operationId: auth#register
            parameters:
                - name: RegisterRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/AuthRegisterRequestBody'
                    required:
                        - username
                        - password
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/AuthRegisterResponseBody'
            schemes:
                - http
    /todos:
        get:
            tags:
                - todo
            summary: list todo
            description: List all todos
            operationId: todo#list
            parameters:
                - name: limit
                  in: query
                  description: Maximum number of todos to return
                  required: false
                  type: integer
                - name: offset
                  in: query
                  description: Offset into the list of todos to start at
                  required: false
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TodoListResponseBody'
            schemes:
                - http
definitions:
    AuthLoginRequestBody:
        title: AuthLoginRequestBody
        type: object
        properties:
            password:
                type: string
                description: Password to login with
                example: Vel officia consequatur.
            username:
                type: string
                description: Username to login with
                example: Quam molestiae molestias rem.
        example:
            password: Qui aut rerum eos quia rem.
            username: Enim dignissimos voluptas.
        required:
            - username
            - password
    AuthLoginResponseBody:
        title: AuthLoginResponseBody
        type: object
        properties:
            token:
                type: string
                description: JWT token to use for authentication
                example: Illo voluptatem doloribus veniam quia.
        example:
            token: Sit porro et.
    AuthLogoutRequestBody:
        title: AuthLogoutRequestBody
        type: object
        properties:
            token:
                type: string
                description: JWT token to use for authentication
                example: Ex voluptatibus autem.
        example:
            token: Qui sit omnis molestiae similique.
        required:
            - token
    AuthRegisterRequestBody:
        title: AuthRegisterRequestBody
        type: object
        properties:
            password:
                type: string
                description: Password to register with
                example: Sapiente voluptas vitae ex quas voluptates.
            username:
                type: string
                description: Username to register with
                example: Itaque optio.
        example:
            password: Quam voluptatem sit voluptatem officia est.
            username: Provident voluptates natus.
        required:
            - username
            - password
    AuthRegisterResponseBody:
        title: AuthRegisterResponseBody
        type: object
        properties:
            token:
                type: string
                description: JWT token to use for authentication
                example: At aut vero.
        example:
            token: Dolorum cupiditate est error magni fugit.
    TodoListResponseBody:
        title: TodoListResponseBody
        type: object
        properties:
            todos:
                $ref: '#/definitions/TodoResponseBodyCollection'
        example:
            todos:
                - createdAt: Aperiam in praesentium totam voluptatibus adipisci eos.
                  createdBy: Deserunt velit ea.
                  description: Quasi facere.
                  done: false
                  doneAt: Mollitia accusantium ut quis voluptatem.
                  doneBy: Libero debitis molestias.
                  id: 2856466262
                  name: Numquam distinctio.
                - createdAt: Aperiam in praesentium totam voluptatibus adipisci eos.
                  createdBy: Deserunt velit ea.
                  description: Quasi facere.
                  done: false
                  doneAt: Mollitia accusantium ut quis voluptatem.
                  doneBy: Libero debitis molestias.
                  id: 2856466262
                  name: Numquam distinctio.
                - createdAt: Aperiam in praesentium totam voluptatibus adipisci eos.
                  createdBy: Deserunt velit ea.
                  description: Quasi facere.
                  done: false
                  doneAt: Mollitia accusantium ut quis voluptatem.
                  doneBy: Libero debitis molestias.
                  id: 2856466262
                  name: Numquam distinctio.
                - createdAt: Aperiam in praesentium totam voluptatibus adipisci eos.
                  createdBy: Deserunt velit ea.
                  description: Quasi facere.
                  done: false
                  doneAt: Mollitia accusantium ut quis voluptatem.
                  doneBy: Libero debitis molestias.
                  id: 2856466262
                  name: Numquam distinctio.
    TodoResponseBody:
        title: 'Mediatype identifier: todo; view=default'
        type: object
        properties:
            createdAt:
                type: string
                description: When the todo was created in ISO format
                example: Autem aliquid odit velit fugiat sint.
            createdBy:
                type: string
                description: Who created the todo
                example: Quis incidunt ut id ad dolores.
            description:
                type: string
                description: Description of the todo
                example: Cum pariatur.
            done:
                type: boolean
                description: Whether or not the todo is done
                example: false
            doneAt:
                type: string
                description: When the todo was done in ISO format
                example: Impedit officiis et repellat.
            doneBy:
                type: string
                description: Who did the todo
                example: Voluptates omnis exercitationem recusandae natus molestiae.
            id:
                type: integer
                description: Unique ID
                example: 1034785665
                format: int32
            name:
                type: string
                description: Name of the todo
                example: Ea aut labore vel est sit.
        description: Todo describes a todo item (default view)
        example:
            createdAt: Inventore laudantium fugiat iusto eaque placeat.
            createdBy: Assumenda ut ut quia error rerum sed.
            description: Cum earum illum at totam.
            done: true
            doneAt: Fugit placeat possimus quo temporibus dolores.
            doneBy: Doloremque et.
            id: 2373087200
            name: Accusantium iusto odit consectetur.
        required:
            - name
            - description
            - done
            - createdAt
    TodoResponseBodyCollection:
        title: 'Mediatype identifier: todo; type=collection; view=default'
        type: array
        items:
            $ref: '#/definitions/TodoResponseBody'
        description: TodoCollectionResponseBody is the result type for an array of TodoResponseBody (default view)
        example:
            - createdAt: Saepe et.
              createdBy: Recusandae corporis et sed.
              description: Assumenda aliquid perspiciatis voluptatem.
              done: false
              doneAt: Amet architecto aut culpa quisquam assumenda.
              doneBy: Repellat culpa ipsum optio at doloribus ea.
              id: 3255721723
              name: Ipsum consequatur nisi dolorem.
            - createdAt: Saepe et.
              createdBy: Recusandae corporis et sed.
              description: Assumenda aliquid perspiciatis voluptatem.
              done: false
              doneAt: Amet architecto aut culpa quisquam assumenda.
              doneBy: Repellat culpa ipsum optio at doloribus ea.
              id: 3255721723
              name: Ipsum consequatur nisi dolorem.
