openapi: 3.0.3
info:
    title: Todo Service
    description: Service for managing todos
    version: "1.0"
servers:
    - url: http://localhost:8000
paths:
    /login:
        post:
            tags:
                - auth
            summary: login auth
            description: Login to the system
            operationId: auth#login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestBody'
                        example:
                            password: Quia rerum enim cupiditate eaque nihil dolore.
                            username: Voluptatum molestias assumenda.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                token: Odit enim nisi.
    /logout:
        post:
            tags:
                - auth
            summary: logout auth
            description: Logout of the system
            operationId: auth#logout
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LogoutRequestBody'
                        example:
                            token: Quasi magni dolor quia et.
            responses:
                "200":
                    description: OK response.
    /register:
        post:
            tags:
                - auth
            summary: register auth
            description: Register a new user
            operationId: auth#register
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LoginRequestBody'
                        example:
                            password: Voluptatem officia vero fugiat cumque ab.
                            username: Eveniet consequatur aut ipsam.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LoginResponseBody'
                            example:
                                token: Dolore voluptatum est voluptatibus cum.
    /todos:
        get:
            tags:
                - todo
            summary: list todo
            description: List all todos
            operationId: todo#list
            parameters:
                - name: limit
                  in: query
                  description: Maximum number of todos to return
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: Maximum number of todos to return
                    example: 2404920389
                  example: 4069445228
                - name: offset
                  in: query
                  description: Offset into the list of todos to start at
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: Offset into the list of todos to start at
                    example: 2922114235
                  example: 88716367
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ListResponseBody'
                            example:
                                todos:
                                    - createdAt: Aperiam in praesentium totam voluptatibus adipisci eos.
                                      createdBy: Deserunt velit ea.
                                      description: Quasi facere.
                                      done: false
                                      doneAt: Mollitia accusantium ut quis voluptatem.
                                      doneBy: Libero debitis molestias.
                                      id: 2856466262
                                      name: Numquam distinctio.
                                    - createdAt: Aperiam in praesentium totam voluptatibus adipisci eos.
                                      createdBy: Deserunt velit ea.
                                      description: Quasi facere.
                                      done: false
                                      doneAt: Mollitia accusantium ut quis voluptatem.
                                      doneBy: Libero debitis molestias.
                                      id: 2856466262
                                      name: Numquam distinctio.
                                    - createdAt: Aperiam in praesentium totam voluptatibus adipisci eos.
                                      createdBy: Deserunt velit ea.
                                      description: Quasi facere.
                                      done: false
                                      doneAt: Mollitia accusantium ut quis voluptatem.
                                      doneBy: Libero debitis molestias.
                                      id: 2856466262
                                      name: Numquam distinctio.
                                    - createdAt: Aperiam in praesentium totam voluptatibus adipisci eos.
                                      createdBy: Deserunt velit ea.
                                      description: Quasi facere.
                                      done: false
                                      doneAt: Mollitia accusantium ut quis voluptatem.
                                      doneBy: Libero debitis molestias.
                                      id: 2856466262
                                      name: Numquam distinctio.
components:
    schemas:
        ListResponseBody:
            type: object
            properties:
                todos:
                    $ref: '#/components/schemas/TodoCollection'
            example:
                todos:
                    - createdAt: Aperiam in praesentium totam voluptatibus adipisci eos.
                      createdBy: Deserunt velit ea.
                      description: Quasi facere.
                      done: false
                      doneAt: Mollitia accusantium ut quis voluptatem.
                      doneBy: Libero debitis molestias.
                      id: 2856466262
                      name: Numquam distinctio.
                    - createdAt: Aperiam in praesentium totam voluptatibus adipisci eos.
                      createdBy: Deserunt velit ea.
                      description: Quasi facere.
                      done: false
                      doneAt: Mollitia accusantium ut quis voluptatem.
                      doneBy: Libero debitis molestias.
                      id: 2856466262
                      name: Numquam distinctio.
                    - createdAt: Aperiam in praesentium totam voluptatibus adipisci eos.
                      createdBy: Deserunt velit ea.
                      description: Quasi facere.
                      done: false
                      doneAt: Mollitia accusantium ut quis voluptatem.
                      doneBy: Libero debitis molestias.
                      id: 2856466262
                      name: Numquam distinctio.
                    - createdAt: Aperiam in praesentium totam voluptatibus adipisci eos.
                      createdBy: Deserunt velit ea.
                      description: Quasi facere.
                      done: false
                      doneAt: Mollitia accusantium ut quis voluptatem.
                      doneBy: Libero debitis molestias.
                      id: 2856466262
                      name: Numquam distinctio.
        LoginRequestBody:
            type: object
            properties:
                password:
                    type: string
                    description: Password to login with
                    example: Aspernatur et possimus voluptatem.
                username:
                    type: string
                    description: Username to login with
                    example: Eum ipsum quam recusandae fuga velit.
            example:
                password: Dolores quis rerum laudantium voluptatem magni.
                username: Sit ex et.
            required:
                - username
                - password
        LoginResponseBody:
            type: object
            properties:
                token:
                    type: string
                    description: JWT token to use for authentication
                    example: Totam est distinctio facilis sint.
            example:
                token: Aut eaque maiores distinctio laudantium corrupti autem.
        LogoutRequestBody:
            type: object
            properties:
                token:
                    type: string
                    description: JWT token to use for authentication
                    example: Nulla qui ipsa molestiae delectus.
            example:
                token: Aliquam iure corrupti alias culpa nobis est.
            required:
                - token
        Todo:
            type: object
            properties:
                createdAt:
                    type: string
                    description: When the todo was created in ISO format
                    example: Itaque quae commodi porro maxime.
                createdBy:
                    type: string
                    description: Who created the todo
                    example: Ut laudantium.
                description:
                    type: string
                    description: Description of the todo
                    example: Ipsam delectus qui ducimus enim assumenda.
                done:
                    type: boolean
                    description: Whether or not the todo is done
                    example: false
                doneAt:
                    type: string
                    description: When the todo was done in ISO format
                    example: Vel cupiditate.
                doneBy:
                    type: string
                    description: Who did the todo
                    example: Saepe mollitia ratione aut dolore quidem ut.
                id:
                    type: integer
                    description: Unique ID
                    example: 3676127781
                name:
                    type: string
                    description: Name of the todo
                    example: Et maiores autem quae esse nisi rerum.
            description: Todo describes a todo item
            example:
                createdAt: Corrupti blanditiis veritatis nihil ab voluptatum.
                createdBy: Et est sed ducimus voluptate.
                description: Esse ut.
                done: false
                doneAt: Voluptatem tempore.
                doneBy: Fugiat doloribus aut.
                id: 1751271024
                name: A labore neque.
            required:
                - name
                - description
                - done
                - createdAt
        TodoCollection:
            type: array
            items:
                $ref: '#/components/schemas/Todo'
            example:
                - createdAt: Aperiam in praesentium totam voluptatibus adipisci eos.
                  createdBy: Deserunt velit ea.
                  description: Quasi facere.
                  done: false
                  doneAt: Mollitia accusantium ut quis voluptatem.
                  doneBy: Libero debitis molestias.
                  id: 2856466262
                  name: Numquam distinctio.
                - createdAt: Aperiam in praesentium totam voluptatibus adipisci eos.
                  createdBy: Deserunt velit ea.
                  description: Quasi facere.
                  done: false
                  doneAt: Mollitia accusantium ut quis voluptatem.
                  doneBy: Libero debitis molestias.
                  id: 2856466262
                  name: Numquam distinctio.
                - createdAt: Aperiam in praesentium totam voluptatibus adipisci eos.
                  createdBy: Deserunt velit ea.
                  description: Quasi facere.
                  done: false
                  doneAt: Mollitia accusantium ut quis voluptatem.
                  doneBy: Libero debitis molestias.
                  id: 2856466262
                  name: Numquam distinctio.
tags:
    - name: auth
      description: The auth service manages authentication
    - name: todo
      description: The todo service manages todo lists
